create extension if not exists pgcrypto;

create table if not exists public.players (
  player_id text primary key
);

alter table public.players
  add column if not exists name text not null default 'Игрок',
  add column if not exists account_code text,
  add column if not exists role text not null default 'Гость кухни',
  add column if not exists avatar_id text not null default 'airfryer',
  add column if not exists department text not null default 'SMM',
  add column if not exists display_name text not null default 'Игрок',
  add column if not exists display_role text not null default 'Гость кухни',
  add column if not exists display_department text not null default 'SMM',
  add column if not exists total_score integer not null default 0,
  add column if not exists rounds integer not null default 0,
  add column if not exists level_points integer not null default 0,
  add column if not exists wallet jsonb not null default '{"coins":0,"inventory":{}}'::jsonb,
  add column if not exists progress jsonb not null default '{"airfryer":0,"blender":0,"coffee":0}'::jsonb,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_id text not null,
  score integer not null default 0,
  difficulty integer not null default 2,
  game text not null default 'match',
  session_id text not null
);

create table if not exists public.duel_rooms (
  room_code text primary key,
  status text not null default 'waiting',
  difficulty text not null default 'normal',
  timer_seconds integer not null default 120,
  seed text not null,
  board jsonb not null default '[]'::jsonb,
  goals jsonb not null default '{}'::jsonb,
  booster_kit jsonb not null default '{}'::jsonb,
  host_player_id text not null,
  guest_player_id text,
  host_profile jsonb not null default '{}'::jsonb,
  guest_profile jsonb,
  host_progress jsonb,
  guest_progress jsonb,
  host_result jsonb,
  guest_result jsonb,
  starts_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.scores
  add column if not exists player_id text,
  add column if not exists score integer not null default 0,
  add column if not exists difficulty integer not null default 2,
  add column if not exists game text not null default 'match',
  add column if not exists session_id text,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists scores_player_session_idx
  on public.scores (player_id, session_id);

create index if not exists players_rating_idx
  on public.players (total_score desc, updated_at asc);

create unique index if not exists players_account_code_idx
  on public.players (account_code)
  where account_code is not null;

create unique index if not exists players_identity_unique_idx
  on public.players (lower(name), lower(role), department);

create index if not exists players_department_rating_idx
  on public.players (department, total_score desc, updated_at asc);

create index if not exists scores_player_created_idx
  on public.scores (player_id, created_at desc);

create index if not exists duel_rooms_status_created_idx
  on public.duel_rooms (status, created_at desc);

create index if not exists duel_rooms_players_idx
  on public.duel_rooms (host_player_id, guest_player_id);

alter table public.players enable row level security;
alter table public.scores enable row level security;
alter table public.duel_rooms enable row level security;

drop policy if exists "Public leaderboard read" on public.players;
drop policy if exists "Public player insert" on public.players;
drop policy if exists "Public player update" on public.players;
drop policy if exists "Players are readable" on public.players;
drop policy if exists "Players are insertable" on public.players;
drop policy if exists "Players are updatable" on public.players;
drop policy if exists "Public scores read" on public.scores;
drop policy if exists "Public scores insert" on public.scores;
drop policy if exists "Scores are readable" on public.scores;
drop policy if exists "Scores are insertable" on public.scores;
drop policy if exists "Duel rooms are readable" on public.duel_rooms;
drop policy if exists "Duel rooms are insertable" on public.duel_rooms;
drop policy if exists "Duel rooms are updatable" on public.duel_rooms;

create policy "Players are readable"
  on public.players for select
  to anon
  using (true);

create policy "Players are insertable"
  on public.players for insert
  to anon
  with check (true);

create policy "Players are updatable"
  on public.players for update
  to anon
  using (true)
  with check (true);

create policy "Scores are readable"
  on public.scores for select
  to anon
  using (true);

create policy "Scores are insertable"
  on public.scores for insert
  to anon
  with check (true);

create policy "Duel rooms are readable"
  on public.duel_rooms for select
  to anon
  using (true);

create policy "Duel rooms are insertable"
  on public.duel_rooms for insert
  to anon
  with check (true);

create policy "Duel rooms are updatable"
  on public.duel_rooms for update
  to anon
  using (true)
  with check (true);
